/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 switch.gltf 
Author: Smoggybeard (https://sketchfab.com/Smoggybeard)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-switch-b30e0a74899b4f9baf030d02f45ab599
Title: Nintendo Switch
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/assets/switch.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.015}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Nintendo_Switch_Nintendo_Switch_Material_0.geometry} material={materials.Nintendo_Switch_Material} position={[0, -0.455, 0]} rotation={[0, -Math.PI / 90, 0]}  scale={3000} />
          {/* rotation={[-Math.PI / 2, 0, 0]} */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/switch.gltf')
